# Group definitions
- name: Install keepalived
  package:
          name: "keepalived"
          state: present
- name: Setup keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
